'''
img_datas = [
'data_10perc/train/CT_Lungs/ct_10per',
'data_10perc/train/CT_Aorta/ct_10per',
'data_10perc/train/CT_AMOS/ct_10per',
'data_10perc/train/CT_COVID19-Infection/ct_10per',
'data_10perc/train/CT_ThoracicOrgans-TCIA-LCTSC/ct_10per',
'data_10perc/train/CT_HaN-Seg/ct_10per',
'data_10perc/train/CT_LiverTumor/ct_10per',
'data_10perc/train/CT_WholeBodyTumor/ct_10per',
'data_10perc/train/CT_AdrenalTumor/ct_10per',
'data_10perc/train/CT_SegRap_HeadNeckTumor/ct_10per',
'data_10perc/train/CT_ColonTumor/ct_10per'
]

'''
'''
img_datas = [
"data_10per/train/oral_cavity_delineation/CT_HaN-Seg",
"data_10per/train/intra-meatal_region_of_vestibular_schwannoma/MR_T1c_crossMoDA_Tumor_Cochlea",
"data_10per/train/left_gluteus_maximus/MR_TotalSeg",
"data_10per/train/left_gluteus_maximus/CT_TotalSeg_muscles",
"data_10per/train/left_iliac_vena/MR_TotalSeg",
"data_10per/train/left_iliac_vena/CT_TotalSeg_cardiac",
"data_10per/train/prostate_lesion/MR_QIN-PROSTATE-Lesion",
"data_10per/train/right_adrenal_gland/MR_TotalSeg",
"data_10per/train/right_adrenal_gland/CT_AMOS",
"data_10per/train/right_adrenal_gland/MR_AMOS",
"data_10per/train/right_adrenal_gland/CT_TotalSeg_organs",
"data_10per/train/right_adrenal_gland/CT_AbdomenAtlas",
"data_10per/train/right_iliac_artery/MR_TotalSeg",
"data_10per/train/right_iliac_artery/CT_TotalSeg_cardiac",
"data_10per/train/right_ventricle_cavity/MR_Heart_ACDC",
"data_10per/train/spleen/MR_CHAOS-T1",
"data_10per/train/spleen/MR_TotalSeg",
"data_10per/train/spleen/MR_CHAOS-T2",
"data_10per/train/spleen/CT_AMOS",
"data_10per/train/spleen/MR_AMOS",
"data_10per/train/spleen/CT_TotalSeg_organs",
"data_10per/train/spleen/CT_AbdomenAtlas",
"data_10per/train/spleen/CT_AbdomenCT1K",
"data_10per/train/arytenoids_delineation/CT_HaN-Seg",
"data_10per/train/lung_lower_lobe_right/CT_TotalSeg_organs",
"data_10per/train/cervical_cancer_tumor/MR_CervicalCancer",
"data_10per/train/stroke_lesion/MR_ISLES_DWI",
"data_10per/train/stroke_lesion/MR_ISLES_ADC",
"data_10per/train/lips/CT_HaN-Seg",
"data_10per/train/left_iliopsoas/MR_TotalSeg",
"data_10per/train/left_iliopsoas/CT_TotalSeg_muscles",
"data_10per/train/right_femur/MR_TotalSeg",
"data_10per/train/right_femur/CT_TotalSeg_muscles",
"data_10per/train/right_clavicula/MR_TotalSeg",
"data_10per/train/right_clavicula/CT_TotalSeg_muscles",
"data_10per/train/inferior_vena_cava/MR_TotalSeg",
"data_10per/train/inferior_vena_cava/CT_TotalSeg_cardiac",
"data_10per/train/inferior_vena_cava/CT_AMOS",
"data_10per/train/inferior_vena_cava/MR_AMOS",
"data_10per/train/right_kidney_cyst/CT_TotalSeg_organs",
"data_10per/train/esophagus/MR_TotalSeg",
"data_10per/train/esophagus/CT_AMOS",
"data_10per/train/esophagus/MR_AMOS",
"data_10per/train/esophagus/CT_TotalSeg_organs",
"data_10per/train/esophagus/CT_ThoracicOrgans-TCIA-LCTSC",
"data_10per/train/esophagus/CT_AbdomenAtlas",
"data_10per/train/liver/MR_CHAOS-T1",
"data_10per/train/liver/MR_TotalSeg",
"data_10per/train/liver/MR_CHAOS-T2",
"data_10per/train/liver/CT_AMOS",
"data_10per/train/liver/MR_AMOS",
"data_10per/train/liver/CT_TotalSeg_organs",
"data_10per/train/liver/CT_AbdomenAtlas",
"data_10per/train/liver/CT_AbdomenCT1K",
"data_10per/train/bladder/CT_AMOS",
"data_10per/train/bladder/MR_AMOS",
"data_10per/train/bladder/CT_AbdomenAtlas",
"data_10per/train/pancreas_tumors/CT_PancreasTumor",
"data_10per/train/left_iliac_artery/MR_TotalSeg",
"data_10per/train/left_iliac_artery/CT_TotalSeg_cardiac",
"data_10per/train/right_hip/MR_TotalSeg",
"data_10per/train/right_hip/CT_TotalSeg_muscles",
"data_10per/train/left_kidney/MR_CHAOS-T1",
"data_10per/train/left_kidney/MR_TotalSeg",
"data_10per/train/left_kidney/MR_CHAOS-T2",
"data_10per/train/left_kidney/CT_AMOS",
"data_10per/train/left_kidney/CT_TotalSeg_organs",
"data_10per/train/left_kidney/CT_AbdomenAtlas",
"data_10per/train/left_kidney/CT_AbdomenCT1K",
"data_10per/train/vertebrae_t10/CT_TotalSeg-vertebrae",
"data_10per/train/left_gluteus_minimus/MR_TotalSeg",
"data_10per/train/left_gluteus_minimus/CT_TotalSeg_muscles",
"data_10per/train/left_brachiocephalic_vein/CT_TotalSeg_cardiac",
"data_10per/train/duodenum/MR_TotalSeg",
"data_10per/train/duodenum/CT_AMOS",
"data_10per/train/duodenum/MR_AMOS",
"data_10per/train/duodenum/CT_TotalSeg_organs",
"data_10per/train/right_gluteus_maximus/MR_TotalSeg",
"data_10per/train/right_gluteus_maximus/CT_TotalSeg_muscles",
"data_10per/train/trachea/CT_TotalSeg_organs",
"data_10per/train/left_clavicula/MR_TotalSeg",
"data_10per/train/left_clavicula/CT_TotalSeg_muscles",
"data_10per/train/right_brachiocephalic_vein/CT_TotalSeg_cardiac",
"data_10per/train/left_gluteus_medius/MR_TotalSeg",
"data_10per/train/left_gluteus_medius/CT_TotalSeg_muscles",
"data_10per/train/spinal_cord/MR_TotalSeg",
"data_10per/train/spinal_cord/CT_TotalSeg_muscles",
"data_10per/train/spinal_cord/CT_ThoracicOrgans-TCIA-LCTSC",
"data_10per/train/spinal_cord/CT_HaN-Seg",
"data_10per/train/gallbladder/MR_TotalSeg",
"data_10per/train/gallbladder/CT_AMOS",
"data_10per/train/gallbladder/MR_AMOS",
"data_10per/train/gallbladder/CT_TotalSeg_organs",
"data_10per/train/gallbladder/CT_AbdomenAtlas",
"data_10per/train/pulmonary_vein/CT_TotalSeg_cardiac",
"data_10per/train/lung_middle_lobe_right/CT_TotalSeg_organs",
"data_10per/train/vertebrae_l4/CT_TotalSeg-vertebrae",
"data_10per/train/left_hip/MR_TotalSeg",
"data_10per/train/left_hip/CT_TotalSeg_muscles",
"data_10per/train/right_submandibular_gland/CT_HaN-Seg",
"data_10per/train/right_optic_nerve/CT_HaN-Seg",
"data_10per/train/right_lung/MR_TotalSeg",
"data_10per/train/right_lung/CT_Lungs",
"data_10per/train/right_lung/CT_ThoracicOrgans-TCIA-LCTSC",
"data_10per/train/vertebrae_t7/CT_TotalSeg-vertebrae",
"data_10per/train/right_cochlea/CT_HaN-Seg",
"data_10per/train/right_cochlea/MR_T1c_crossMoDA_Tumor_Cochlea",
"data_10per/train/intervertebral_discs/MR_TotalSeg",
"data_10per/train/left_adrenal_gland/MR_TotalSeg",
"data_10per/train/left_adrenal_gland/CT_AMOS",
"data_10per/train/left_adrenal_gland/MR_AMOS",
"data_10per/train/left_adrenal_gland/CT_TotalSeg_organs",
"data_10per/train/left_adrenal_gland/CT_AbdomenAtlas",
"data_10per/train/right_gluteus_minimus/MR_TotalSeg",
"data_10per/train/right_gluteus_minimus/CT_TotalSeg_muscles",
"data_10per/train/postcava/CT_AbdomenAtlas",
"data_10per/train/right_subclavian_artery/CT_TotalSeg_cardiac",
"data_10per/train/vertebrae_c1/CT_TotalSeg-vertebrae",
"data_10per/train/larynx-supraglottic/CT_HaN-Seg",
"data_10per/train/white_matter_hyperintensities/MR_WMH_T1",
"data_10per/train/white_matter_hyperintensities/MR_WMH_FLAIR",
"data_10per/train/vertebrae_l5/CT_TotalSeg-vertebrae",
"data_10per/train/thyroid/CT_HaN-Seg",
"data_10per/train/heart/MR_TotalSeg",
"data_10per/train/heart/CT_TotalSeg_cardiac",
"data_10per/train/heart/CT_ThoracicOrgans-TCIA-LCTSC",
"data_10per/train/liver_tumors/CT_LiverTumor",
"data_10per/train/right_posterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/train/vertebrae_c3/CT_TotalSeg-vertebrae",
"data_10per/train/mandible/CT_HaN-Seg",
"data_10per/train/right_autochthon/MR_TotalSeg",
"data_10per/train/right_autochthon/CT_TotalSeg_muscles",
"data_10per/train/prostate/MR_TotalSeg",
"data_10per/train/prostate/CT_AMOS",
"data_10per/train/prostate/MR_ProstateT2",
"data_10per/train/prostate/CT_TotalSeg_organs",
"data_10per/train/superior_vena_cava/CT_TotalSeg_cardiac",
"data_10per/train/left_anterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/train/left_lung/MR_TotalSeg",
"data_10per/train/left_lung/CT_Lungs",
"data_10per/train/left_lung/CT_ThoracicOrgans-TCIA-LCTSC",
"data_10per/train/buccal_mucosa/CT_HaN-Seg",
"data_10per/train/colon/MR_TotalSeg",
"data_10per/train/colon/CT_TotalSeg_organs",
"data_10per/train/right_gluteus_medius/MR_TotalSeg",
"data_10per/train/right_gluteus_medius/CT_TotalSeg_muscles",
"data_10per/train/surrounding_non-enhancing_flair_hyperintensit/MR_BraTS-T1n",
"data_10per/train/surrounding_non-enhancing_flair_hyperintensit/MR_BraTS-T1c",
"data_10per/train/surrounding_non-enhancing_flair_hyperintensit/MR_BraTS-T2f",
"data_10per/train/colon_cancer_primaries/CT_ColonTumor",
"data_10per/train/right_carotid_artery/CT_HaN-Seg",
"data_10per/train/vertebrae_t1/CT_TotalSeg-vertebrae",
"data_10per/train/left_optic_nerve/CT_HaN-Seg",
"data_10per/train/lymph_node/CT_LymphNode",
"data_10per/train/covid-19_infection/CT_COVID19-Infection",
"data_10per/train/small_bowel/MR_TotalSeg",
"data_10per/train/small_bowel/CT_TotalSeg_organs",
"data_10per/train/urinary_bladder/MR_TotalSeg",
"data_10per/train/urinary_bladder/CT_TotalSeg_organs",
"data_10per/train/vertebrae_c4/CT_TotalSeg-vertebrae",
"data_10per/train/lung_lesions/CT_LungLesion",
"data_10per/train/vertebrae_l1/CT_TotalSeg-vertebrae",
"data_10per/train/sacrum/MR_TotalSeg",
"data_10per/train/sacrum/CT_TotalSeg-vertebrae",
"data_10per/train/enhancing_tissue/MR_BraTS-T1n",
"data_10per/train/enhancing_tissue/MR_BraTS-T1c",
"data_10per/train/enhancing_tissue/MR_BraTS-T2f",
"data_10per/train/enhancing_tissue/MR_BraTS-T2w",
"data_10per/train/vertebrae_t12/CT_TotalSeg-vertebrae",
"data_10per/train/left_femur/MR_TotalSeg",
"data_10per/train/left_femur/CT_TotalSeg_muscles",
"data_10per/train/stomach/MR_TotalSeg",
"data_10per/train/stomach/CT_AMOS",
"data_10per/train/stomach/MR_AMOS",
"data_10per/train/stomach/CT_TotalSeg_organs",
"data_10per/train/stomach/CT_AbdomenAtlas",
"data_10per/train/right_scapula/MR_TotalSeg",
"data_10per/train/right_scapula/CT_TotalSeg_muscles",
"data_10per/train/lung_upper_lobe_left/CT_TotalSeg_organs",
"data_10per/train/thyroid_gland/CT_TotalSeg_organs",
"data_10per/train/aorta/MR_TotalSeg",
"data_10per/train/aorta/CT_TotalSeg_cardiac",
"data_10per/train/aorta/CT_AMOS",
"data_10per/train/aorta/MR_AMOS",
"data_10per/train/aorta/CT_AbdomenAtlas",
"data_10per/train/right_parotid_gland/CT_HaN-Seg",
"data_10per/train/vertebrae_l3/CT_TotalSeg-vertebrae",
"data_10per/train/vertebrae_t9/CT_TotalSeg-vertebrae",
"data_10per/train/vertebrae_c5/CT_TotalSeg-vertebrae",
"data_10per/train/pancreas/MR_TotalSeg",
"data_10per/train/pancreas/CT_AMOS",
"data_10per/train/pancreas/MR_AMOS",
"data_10per/train/pancreas/CT_TotalSeg_organs",
"data_10per/train/pancreas/CT_AbdomenAtlas",
"data_10per/train/pancreas/CT_AbdomenCT1K",
"data_10per/train/myocardium/MR_Heart_ACDC",
"data_10per/train/pituitary_gland/CT_HaN-Seg",
"data_10per/train/transition_zone/MR_ProstateADC",
"data_10per/train/vertebrae_t11/CT_TotalSeg-vertebrae",
"data_10per/train/left_carotid_artery/CT_HaN-Seg",
"data_10per/train/larynx-glottis/CT_HaN-Seg",
"data_10per/train/left_ventricle_cavity/MR_Heart_ACDC",
"data_10per/train/vertebrae/MR_TotalSeg",
"data_10per/train/vertebrae_c6/CT_TotalSeg-vertebrae",
"data_10per/train/optic_chiasm/CT_HaN-Seg",
"data_10per/train/left_common_carotid_artery/CT_TotalSeg_cardiac",
"data_10per/train/vertebrae_l2/CT_TotalSeg-vertebrae",
"data_10per/train/vertebrae_t5/CT_TotalSeg-vertebrae",
"data_10per/train/vertebrae_s1/CT_TotalSeg-vertebrae",
"data_10per/train/left_renal_structure_identified_via_abdominal_magnetic_resonance/MR_AMOS",
"data_10per/train/vertebrae_t3/CT_TotalSeg-vertebrae",
"data_10per/train/cervical_esophagus/CT_HaN-Seg",
"data_10per/train/left_kidney_cyst/CT_TotalSeg_organs",
"data_10per/train/left_autochthon/MR_TotalSeg",
"data_10per/train/left_autochthon/CT_TotalSeg_muscles",
"data_10per/train/left_atrial_appendage/CT_TotalSeg_cardiac",
"data_10per/train/right_kidney/MR_CHAOS-T1",
"data_10per/train/right_kidney/MR_TotalSeg",
"data_10per/train/right_kidney/MR_CHAOS-T2",
"data_10per/train/right_kidney/CT_AMOS",
"data_10per/train/right_kidney/MR_AMOS",
"data_10per/train/right_kidney/CT_TotalSeg_organs",
"data_10per/train/right_kidney/CT_AbdomenAtlas",
"data_10per/train/right_kidney/CT_AbdomenCT1K",
"data_10per/train/cricopharyngeal_inlet/CT_HaN-Seg",
"data_10per/train/vertebrae_t8/CT_TotalSeg-vertebrae",
"data_10per/train/skull/CT_TotalSeg_muscles",
"data_10per/train/right_iliopsoas/MR_TotalSeg",
"data_10per/train/right_iliopsoas/CT_TotalSeg_muscles",
"data_10per/train/brainstem/CT_HaN-Seg",
"data_10per/train/vertebrae_c2/CT_TotalSeg-vertebrae",
"data_10per/train/right_common_carotid_artery/CT_TotalSeg_cardiac",
"data_10per/train/lung_upper_lobe_right/CT_TotalSeg_organs",
"data_10per/train/lesion/CT_WholeBodyTumor",
"data_10per/train/resection_cavity/MR_BraTS-T1n",
"data_10per/train/resection_cavity/MR_BraTS-T1c",
"data_10per/train/resection_cavity/MR_BraTS-T2f",
"data_10per/train/resection_cavity/MR_BraTS-T2w",
"data_10per/train/left_atrium/MR_LeftAtrium",
"data_10per/train/vertebrae_t6/CT_TotalSeg-vertebrae",
"data_10per/train/vertebrae_c7/CT_TotalSeg-vertebrae",
"data_10per/train/right_humerus/MR_TotalSeg",
"data_10per/train/right_humerus/CT_TotalSeg_muscles",
"data_10per/train/right_iliac_vena/MR_TotalSeg",
"data_10per/train/right_iliac_vena/CT_TotalSeg_cardiac",
"data_10per/train/right_anterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/train/left_cochlea/CT_HaN-Seg",
"data_10per/train/left_cochlea/MR_T1c_crossMoDA_Tumor_Cochlea",
"data_10per/train/left_parotid_gland/CT_HaN-Seg",
"data_10per/train/vertebrae_t2/CT_TotalSeg-vertebrae",
"data_10per/train/vertebrae_t4/CT_TotalSeg-vertebrae",
"data_10per/train/surrounding_non-enhancing_flair_hyperintensity/MR_BraTS-T2w",
"data_10per/train/left_scapula/MR_TotalSeg",
"data_10per/train/left_scapula/CT_TotalSeg_muscles",
"data_10per/train/head-neck_cancer/CT_SegRap_HeadNeckTumor",
"data_10per/train/left_lacrimal_gland/CT_HaN-Seg",
"data_10per/train/lung_lower_lobe_left/CT_TotalSeg_organs",
"data_10per/train/left_posterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/train/brachiocephalic_trunk/CT_TotalSeg_cardiac",
"data_10per/train/left_submandibular_gland/CT_HaN-Seg",
"data_10per/train/left_humerus/MR_TotalSeg",
"data_10per/train/left_humerus/CT_TotalSeg_muscles",
"data_10per/train/portal_vein_and_splenic_vein/MR_TotalSeg",
"data_10per/train/portal_vein_and_splenic_vein/CT_TotalSeg_cardiac",
"data_10per/train/extra-meatal_region_of_vestibular_schwannoma/MR_T1c_crossMoDA_Tumor_Cochlea",
"data_10per/train/left_subclavian_artery/CT_TotalSeg_cardiac",
"data_10per/train/non-enhancing_tumor_core/MR_BraTS-T1n",
"data_10per/train/non-enhancing_tumor_core/MR_BraTS-T1c",
"data_10per/train/non-enhancing_tumor_core/MR_BraTS-T2f",
"data_10per/train/non-enhancing_tumor_core/MR_BraTS-T2w",
"data_10per/train/brain/MR_TotalSeg",
"data_10per/train/brain/CT_TotalSeg_muscles"
]

'''
img_datas = [
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_101_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_113_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_55_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Inferior_vena_cava/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Inferior_vena_cava/CT_AMOS",
"data_10per/val_with_organ (copy)/Inferior_vena_cava/MR_AMOS",
"data_10per/val_with_organ (copy)/Inferior_vena_cava/MR_totalseg",
"data_10per/val_with_organ (copy)/Surrounding_non-enhancing_FLAIR_hyperintensity/MR_BraTS-T2w",
"data_10per/val_with_organ (copy)/Vertebrae_S1/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/MR_Heart_la_label_1_description_1/MR_Heart_la",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_53_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_1_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_AbdTumor_HCC_label_1_description_1/CT_AbdTumor_HCC",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_77_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_26_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Mandible/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Brachiocephalic_trunk/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_31_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_112_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_T2/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Right_anterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_7_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_96_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_127_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_15_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Esophagus/CT_AMOS",
"data_10per/val_with_organ (copy)/Esophagus/MR_AMOS",
"data_10per/val_with_organ (copy)/Esophagus/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Esophagus/MR_totalseg",
"data_10per/val_with_organ (copy)/Esophagus/CT_TCIA-LCTSC",
"data_10per/val_with_organ (copy)/Surrounding_non-enhancing_FLAIR_hyperintensit/MR_BraTS-T1n",
"data_10per/val_with_organ (copy)/Surrounding_non-enhancing_FLAIR_hyperintensit/MR_BraTS-T1c",
"data_10per/val_with_organ (copy)/Surrounding_non-enhancing_FLAIR_hyperintensit/MR_BraTS-T2f",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_5_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_24_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_21_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_37_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Bladder/CT_AMOS",
"data_10per/val_with_organ (copy)/Bladder/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_54_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_C7/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_17_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Lung_upper_lobe_left/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_126_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_64_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_122_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_GTVpNCCT_segrap_label_1_description_1/CT_GTVpNCCT_segrap",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_21_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_2_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_93_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_83_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/GTVp_and_GTVn_tumor/MR_Head_HNTSMRG24",
"data_10per/val_with_organ (copy)/Larynx-supraglottic/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_106_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_94_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_105_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_79_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Adrenocortical_carcinoma/CT_AbdTumor_Adrenal",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_137_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_25_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_109_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_45_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_11_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_133_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_anterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Lips/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_16_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_17_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_81_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_47_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_iliopsoas/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Liver_tumors/CT_AbdTumor_liver",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_135_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_13_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_67_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_kidney/MR_CHAOS-T1",
"data_10per/val_with_organ (copy)/Right_kidney/MR_CHAOS-T2",
"data_10per/val_with_organ (copy)/Right_kidney/CT_AMOS",
"data_10per/val_with_organ (copy)/Right_kidney/MR_AMOS",
"data_10per/val_with_organ (copy)/Right_kidney/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Right_kidney/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_kidney/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Enhancing_tissue/MR_BraTS-T1n",
"data_10per/val_with_organ (copy)/Enhancing_tissue/MR_BraTS-T1c",
"data_10per/val_with_organ (copy)/Enhancing_tissue/MR_BraTS-T2f",
"data_10per/val_with_organ (copy)/Enhancing_tissue/MR_BraTS-T2w",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_97_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_T11/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Left_renal_structure_identified_via_abdominal_magnetic_resonance/MR_AMOS",
"data_10per/val_with_organ (copy)/Pancreas_tumors/CT_AbdTumor_pancreas",
"data_10per/val_with_organ (copy)/Sacrum/MR_totalseg",
"data_10per/val_with_organ (copy)/Sacrum/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Vertebrae_T5/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Thyroid/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_76_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_61_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_49_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_4_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Left_clavicula/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_clavicula/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_clavicula/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_clavicula/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_scapula/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_scapula/MR_totalseg",
"data_10per/val_with_organ (copy)/Brainstem/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_19_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_L1/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Brain/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_5_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/White_matter_hyperintensities/MR_WMH_T1",
"data_10per/val_with_organ (copy)/White_matter_hyperintensities/MR_WMH_FLAIR",
"data_10per/val_with_organ (copy)/Left_autochthon/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_autochthon/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_66_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_65_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Lung_upper_lobe_right/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_115_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Gallbladder/CT_AMOS",
"data_10per/val_with_organ (copy)/Gallbladder/MR_AMOS",
"data_10per/val_with_organ (copy)/Gallbladder/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Gallbladder/MR_totalseg",
"data_10per/val_with_organ (copy)/Gallbladder/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_35_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_3_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Portal_vein_and_splenic_vein/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Portal_vein_and_splenic_vein/MR_totalseg",
"data_10per/val_with_organ (copy)/Lung_middle_lobe_right/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_118_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_44_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Skull/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_125_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_78_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_128_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Superior_vena_cava/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Left_optic_nerve/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Prostate/uterus",
"data_10per/val_with_organ (copy)/Prostate/MR_ProstateT2",
"data_10per/val_with_organ (copy)/Prostate/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Prostate/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_84_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Thyroid_gland/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_110_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Arytenoids_delineation/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_50_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_91_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_48_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Pituitary_gland/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Vertebrae_T8/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Right_humerus/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_humerus/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_36_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Spleen/MR_CHAOS-T1",
"data_10per/val_with_organ (copy)/Spleen/MR_CHAOS-T2",
"data_10per/val_with_organ (copy)/Spleen/CT_AMOS",
"data_10per/val_with_organ (copy)/Spleen/MR_AMOS",
"data_10per/val_with_organ (copy)/Spleen/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Spleen/MR_totalseg",
"data_10per/val_with_organ (copy)/Spleen/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Vertebrae_L5/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Left_adrenal_gland/CT_AMOS",
"data_10per/val_with_organ (copy)/Left_adrenal_gland/MR_AMOS",
"data_10per/val_with_organ (copy)/Left_adrenal_gland/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Left_adrenal_gland/MR_totalseg",
"data_10per/val_with_organ (copy)/Left_adrenal_gland/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_73_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_7_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Right_common_carotid_artery/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Larynx-glottis/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Left_parotid_gland/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_72_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_3_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Airway_Tree/CT_AirwayTree",
"data_10per/val_with_organ (copy)/Right_subclavian_artery/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_63_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_T6/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Left_hip/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_hip/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_46_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_femur/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_femur/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_4_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Lung_lesions/CT_LungLesion",
"data_10per/val_with_organ (copy)/Intervertebral_discs/MR_Spider_IVD",
"data_10per/val_with_organ (copy)/Intervertebral_discs/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_59_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Cervical_esophagus/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_case_label_3_description_1/CT_AbdTumor_case",
"data_10per/val_with_organ (copy)/Left_posterior_segment_of_the_eyeball/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Prostate_lesion/MR_QIN-PROSTATE",
"data_10per/val_with_organ (copy)/Spinal_canal/MR_Spider_Spine",
"data_10per/val_with_organ (copy)/Right_submandibular_gland/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Myocardium/MR_heart-ACDC",
"data_10per/val_with_organ (copy)/Myocardium/US_Cardiac",
"data_10per/val_with_organ (copy)/Vertebrae_C5/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Left_Ventricle/US_Cardiac",
"data_10per/val_with_organ (copy)/Vertebrae_T1/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Left_gluteus_maximus/MR_totalseg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_case_label_1_description_1/CT_AbdTumor_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_95_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_27_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_62_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_82_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_humerus/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_humerus/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_autochthon/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Non-enhancing_tumor_core/MR_BraTS-T1n",
"data_10per/val_with_organ (copy)/Non-enhancing_tumor_core/MR_BraTS-T1c",
"data_10per/val_with_organ (copy)/Non-enhancing_tumor_core/MR_BraTS-T2f",
"data_10per/val_with_organ (copy)/Non-enhancing_tumor_core/MR_BraTS-T2w",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_39_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_T7/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Resection_cavity/MR_BraTS-T1n",
"data_10per/val_with_organ (copy)/Resection_cavity/MR_BraTS-T1c",
"data_10per/val_with_organ (copy)/Resection_cavity/MR_BraTS-T2f",
"data_10per/val_with_organ (copy)/Resection_cavity/MR_BraTS-T2w",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_58_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Lymph_node/CT_LNQ_LymphNode",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_124_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_86_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_25_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_adrenal_gland/CT_AMOS",
"data_10per/val_with_organ (copy)/Right_adrenal_gland/MR_AMOS",
"data_10per/val_with_organ (copy)/Right_adrenal_gland/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Right_adrenal_gland/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_adrenal_gland/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_120_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_134_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_71_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_iliac_vena/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Right_iliac_vena/MR_totalseg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_5_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_57_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_12_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Left_subclavian_artery/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Vertebrae_T9/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_7_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_136_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_19_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Right_gluteus_maximus/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_gluteus_maximus/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_optic_nerve/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_9_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Vertebrae_C3/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_13_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Vertebrae/MR_Spider_Vertebrae",
"data_10per/val_with_organ (copy)/Vertebrae/MR_totalseg",
"data_10per/val_with_organ (copy)/Stroke_lesion/MR_ISLES2022_DWI",
"data_10per/val_with_organ (copy)/Stroke_lesion/MR_ISLES2022_ADC",
"data_10per/val_with_organ (copy)/Vertebrae_C4/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Transition_zone/MR_ProstateADC",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_10_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_27_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_33_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_AbdTumor_case_label_2_description_1/CT_AbdTumor_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_22_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_92_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_60_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_119_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_117_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_26_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Oral_cavity_delineation/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_34_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Pancreas/CT_AMOS",
"data_10per/val_with_organ (copy)/Pancreas/MR_AMOS",
"data_10per/val_with_organ (copy)/Pancreas/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Pancreas/MR_totalseg",
"data_10per/val_with_organ (copy)/Pancreas/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Left_atrial_appendage/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_1_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_80_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_132_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_52_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_L4/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Pulmonary_vein/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_129_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_parotid_gland/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Right_brachiocephalic_vein/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Vertebrae_T3/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_87_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_lung/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_lung/CT_TCIA-LCTSC",
"data_10per/val_with_organ (copy)/Right_lung/CT_LungMasks",
"data_10per/val_with_organ (copy)/Extra-meatal_region_of_vestibular_schwannoma/MR_crossmoda",
"data_10per/val_with_organ (copy)/Vertebrae_T12/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_70_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_130_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_T4/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_8_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_89_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Trachea/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_28_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_10_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Liver/MR_CHAOS-T1",
"data_10per/val_with_organ (copy)/Liver/MR_CHAOS-T2",
"data_10per/val_with_organ (copy)/Liver/CT_AMOS",
"data_10per/val_with_organ (copy)/Liver/MR_AMOS",
"data_10per/val_with_organ (copy)/Liver/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Liver/MR_totalseg",
"data_10per/val_with_organ (copy)/Liver/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Spinal_cord/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Spinal_cord/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Spinal_cord/MR_totalseg",
"data_10per/val_with_organ (copy)/Spinal_cord/CT_TCIA-LCTSC",
"data_10per/val_with_organ (copy)/Gastrocnemius_Lateralis/US_Low-limb-Leg",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_11_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Left_gluteus_Maximus/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Intra-meatal_region_of_vestibular_schwannoma/MR_crossmoda",
"data_10per/val_with_organ (copy)/Lesion/PET_autoPET",
"data_10per/val_with_organ (copy)/Aorta/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Aorta/CT_AMOS",
"data_10per/val_with_organ (copy)/Aorta/MR_AMOS",
"data_10per/val_with_organ (copy)/Aorta/MR_totalseg",
"data_10per/val_with_organ (copy)/Aorta/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_56_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_brachiocephalic_vein/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Right_hip/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_hip/MR_totalseg",
"data_10per/val_with_organ (copy)/CT_GTVpEnhance_segrap_label_1_description_1/CT_GTVpEnhance_segrap",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_38_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_111_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_2_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Vertebrae_T10/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Vertebrae_L2/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_16_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_74_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_29_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Stomach/CT_AMOS",
"data_10per/val_with_organ (copy)/Stomach/MR_AMOS",
"data_10per/val_with_organ (copy)/Stomach/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Stomach/MR_totalseg",
"data_10per/val_with_organ (copy)/Stomach/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_42_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_41_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_12_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_68_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_107_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_iliac_artery/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Right_iliac_artery/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_30_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_108_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Soleus/US_Low-limb-Leg",
"data_10per/val_with_organ (copy)/COVID-19_infection/CT_COVID",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_69_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_femur/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_femur/MR_totalseg",
"data_10per/val_with_organ (copy)/Left_lung/MR_totalseg",
"data_10per/val_with_organ (copy)/Left_lung/CT_TCIA-LCTSC",
"data_10per/val_with_organ (copy)/Left_lung/CT_LungMasks",
"data_10per/val_with_organ (copy)/Small_bowel/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Small_bowel/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_cochlea/MR_crossmoda",
"data_10per/val_with_organ (copy)/Right_cochlea/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_6_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_121_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Right_gluteus_medius/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_gluteus_medius/MR_totalseg",
"data_10per/val_with_organ (copy)/Postcava/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_75_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Buccal_mucosa/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Colon_cancer_primaries/CT_AbdTumor_colon",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_98_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_23_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_18_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_103_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_43_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_C1/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_6_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_123_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_22_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Right_gluteus_minimus/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Right_gluteus_minimus/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_104_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_1_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_4_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Left_gluteus_medius/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_gluteus_medius/MR_totalseg",
"data_10per/val_with_organ (copy)/Right_ventricle_cavity/MR_heart-ACDC",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_14_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Vertebrae_C2/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_20_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Left_common_carotid_artery/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_14_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_114_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_51_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Gastrocnemius_Medialis/US_Low-limb-Leg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_116_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_Atrium/US_Cardiac",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_40_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_3_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Lung_lower_lobe_left/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_6_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Vertebrae_L3/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Colon/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Colon/MR_totalseg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_case_label_4_description_1/CT_AbdTumor_case",
"data_10per/val_with_organ (copy)/Left_kidney/MR_CHAOS-T1",
"data_10per/val_with_organ (copy)/Left_kidney/MR_CHAOS-T2",
"data_10per/val_with_organ (copy)/Left_kidney/CT_AMOS",
"data_10per/val_with_organ (copy)/Left_kidney/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Left_kidney/MR_totalseg",
"data_10per/val_with_organ (copy)/Left_kidney/CT_AbdomenAtlas",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_100_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_AbdTumor_hepaticvessel_label_1_description_1/CT_AbdTumor_hepaticvessel",
"data_10per/val_with_organ (copy)/Left_lacrimal_gland/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_9_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_18_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Lung_lower_lobe_right/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Optic_chiasm/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_23_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Urinary_bladder/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Urinary_bladder/MR_totalseg",
"data_10per/val_with_organ (copy)/Vertebrae_C6/CT_totalseg-vertebrae",
"data_10per/val_with_organ (copy)/Left_iliac_artery/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Left_iliac_artery/MR_totalseg",
"data_10per/val_with_organ (copy)/Cricopharyngeal_inlet/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Aortic_vessel_trees/CT_Aorta",
"data_10per/val_with_organ (copy)/Left_scapula/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_scapula/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_131_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_99_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_8_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Left_kidney_cyst/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_24_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Duodenum/CT_AMOS",
"data_10per/val_with_organ (copy)/Duodenum/MR_AMOS",
"data_10per/val_with_organ (copy)/Duodenum/CT_TotalSeg_organs",
"data_10per/val_with_organ (copy)/Duodenum/MR_totalseg",
"data_10per/val_with_organ (copy)/Left_iliac_vena/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Left_iliac_vena/MR_totalseg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_9_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_iliopsoas/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_88_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_102_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_28_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/MR_HeadHaN_case_label_15_description_1/MR_HeadHaN_case",
"data_10per/val_with_organ (copy)/Left_carotid_artery/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_8_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_90_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Left_gluteus_minimus/CT_TotalSeg_muscles",
"data_10per/val_with_organ (copy)/Left_gluteus_minimus/MR_totalseg",
"data_10per/val_with_organ (copy)/CT_AbdTumor_PETCT_label_2_description_1/CT_AbdTumor_PETCT",
"data_10per/val_with_organ (copy)/Left_submandibular_gland/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_85_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Heart/CT_TotalSeg_cardiac",
"data_10per/val_with_organ (copy)/Heart/MR_totalseg",
"data_10per/val_with_organ (copy)/Heart/CT_TCIA-LCTSC",
"data_10per/val_with_organ (copy)/Right_carotid_artery/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Left_cochlea/CT_HaN-Seg",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_20_description_1/Microscopy_SELMA3D_patchvolume",
"data_10per/val_with_organ (copy)/Microscopy_SELMA3D_patchvolume_label_32_description_1/Microscopy_SELMA3D_patchvolume"
]







all_datasets = [
'AMOS2022_ct',
'AMOS2022_mr_unknown',
'ATLAS2_mr_t1w',
'ATM2022_ct',
'AbdomenCT1K_ct',
'BTCV_Abdomen_ct',
'BTCV_Cervix_ct',
'BraTS2021_mr_flair',
'BraTS2021_mr_t1',
'BraTS2021_mr_t1ce',
'BraTS2021_mr_t2',
'BrainPTM2021_mr_t1',
'BrainTumour_mr_flair',
'BrainTumour_mr_t1gd',
'BrainTumour_mr_t1w',
'BrainTumour_mr_t2w',
'CAUSE07_mr_unknown',
'COVID1920_ct',
'COVID19CTscans_ct',
'CTORG_ct',
'CTPelvic1k_ct',
'CTSpine1K_ct',
'Chest_CT_Scans_with_COVID-19_ct',
'FLARE21_ct',
'FeTA2022_mr_t2w',
'HeadandNeckAutoSegmentationChallenge_ct',
'HeartSegMRI_mr_unknown',
'ISLES2022_mr_adc',
'ISLES2022_mr_dwi',
'KiPA22_ct',
'LAScarQS22Task1_mr_lge',
'LAScarQS22Task2_mr_lge',
'LITS_ct',
'LNDb_ct',
'LUNA16_ct',
'LongitudinalMultipleSclerosisLesionSegmentation_mr_flair',
'LongitudinalMultipleSclerosisLesionSegmentation_mr_mprage',
'LongitudinalMultipleSclerosisLesionSegmentation_mr_pd',
'LongitudinalMultipleSclerosisLesionSegmentation_mr_t2',
'MESSEG_mr_flair',
'MMWHS_ct',
'MRBrain18_mr_t1',
'MRBrain18_mr_t1ir',
'MRBrain18_mr_t2flair',
'MRBrainS13_mr_t1',
'MRBrainS13_mr_t1ir',
'MRBrainS13_mr_t2flair',
'MSD02_Heart_mr_unknown',
'MSD04_Hippocampus_mr_unknown',
'MSD05_Prostate_mr_adc',
'MSD05_Prostate_mr_t2',
'MSD06_Lung_ct',
'MSD07_Pancreas_ct',
'MSD08_HepaticVessel_ct',
'MSD09_Spleen_ct',
'MSD10_Colon_ct',
'MSseg08_mr_flair',
'MSseg08_mr_t1',
'MSseg08_mr_t2',
'PROMISE12_mr_unknown',
'Prostate_MRI_Segmentation_Dataset_mr_t2w',
'RibFrac2020_ct',
'SLIVER07_ct',
'SegThor_ct',
'StructSeg2019_subtask1_ct',
'StructSeg2019_subtask2_ct',
'StructSeg2019_subtask3_ct',
'StructSeg2019_subtask4_ct',
'Totalsegmentator_dataset_ct',
'VALDO_Task2_mr_t2s',
'VESSEL2012_ct',
'WMH_mr_flair',
'WMH_mr_t1',
'WORD_ct',
'cSeg-2022_mr_unknown',
'iSeg2017_mr_t1',
'iSeg2017_mr_t2',
'iseg2019_mr_t1',
'iseg2019_mr_t2',
'mnms_mr_unknown',
]